"""add course_id to payment transactions

Revision ID: 6d936a60c31e
Revises: d10de9b1236b
Create Date: 2026-08-02 15:58:20.171023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d936a60c31e'
down_revision: Union[str, Sequence[str], None] = 'd10de9b1236b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('course_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'course_id')
    # ### end Alembic commands ###
