"""add auto renew to subscriptions

Revision ID: 922b9af8306b
Revises: b4aed1b26ae3
Create Date: 2026-06-07 16:19:41.025114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922b9af8306b'
down_revision: Union[str, Sequence[str], None] = 'b4aed1b26ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'auto_renew')
    # ### end Alembic commands ###
