"""add creator billing and withdrawal safety

Revision ID: 94cd4fd7a9cf
Revises: 6d936a60c31e
Create Date: 2026-08-16 12:10:36.866055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cd4fd7a9cf'
down_revision: Union[str, Sequence[str], None] = '6d936a60c31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payment_transactions', 'commission_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('subscription_plans', sa.Column('code', sa.String(), nullable=True))
    op.add_column('subscription_plans', sa.Column('max_courses', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_subscription_plans_code', 'subscription_plans', ['code'])
    op.alter_column('wallet_ledger', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('wallets', 'pending_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('wallets', 'lifetime_earned',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('wallets', 'lifetime_withdrawn',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('withdrawals', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('payout_provider', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('payout_reference', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('failure_reason', sa.String(), nullable=True))
    op.alter_column('withdrawals', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdrawals', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('withdrawals', 'failure_reason')
    op.drop_column('withdrawals', 'payout_reference')
    op.drop_column('withdrawals', 'payout_provider')
    op.drop_column('withdrawals', 'idempotency_key')
    op.alter_column('wallets', 'lifetime_withdrawn',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('wallets', 'lifetime_earned',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('wallets', 'pending_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('wallet_ledger', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint('uq_subscription_plans_code', 'subscription_plans', type_='unique')
    op.drop_column('subscription_plans', 'max_courses')
    op.drop_column('subscription_plans', 'code')
    op.alter_column('payment_transactions', 'commission_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
