"""create payment transactions

Revision ID: c01adff6a228
Revises: a9ca0dfccdde
Create Date: 2026-06-07 15:34:14.772066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01adff6a228'
down_revision: Union[str, Sequence[str], None] = 'a9ca0dfccdde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payer_id', sa.String(), nullable=False),
    sa.Column('payee_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('payment_provider', sa.String(), nullable=False),
    sa.Column('provider_order_id', sa.String(), nullable=True),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
