"""add payment provider to subscriptions

Revision ID: edd99d108806
Revises: 922b9af8306b
Create Date: 2026-06-07 16:22:18.362713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd99d108806'
down_revision: Union[str, Sequence[str], None] = '922b9af8306b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'payment_provider')
    # ### end Alembic commands ###
