"""add plan id to payment transactions

Revision ID: f11e36f3b773
Revises: edd99d108806
Create Date: 2026-06-09 12:39:53.172334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11e36f3b773'
down_revision: Union[str, Sequence[str], None] = 'edd99d108806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('plan_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'plan_id')
    # ### end Alembic commands ###
